[workspace]
resolver = "2"
members = [
    "crates/mqtt-packet",
    "crates/mqtt-embedded",
    "crates/mqtt-tokio",
    "crates/mqtt-bridges",
    "crates/mqtt-async-embedded",
    "benches",
]

[workspace.package]
version = "1.6.0"
edition = "2024"
authors = ["Faez Barghasa <faez.barghasa.org@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/FaezBarghasa/mqtt-async-embedded"
documentation = "https://docs.rs/mqtt-async-embedded"
readme = "README.md"
keywords = ["mqtt", "async", "embedded", "embassy", "no_std"]
categories = ["embedded", "no-std", "asynchronous", "network-programming"]
