[package]
name = "mqtt-async-embedded"
version = "1.0.0"
edition = "2024"
authors = ["Faez Barghasa <faez.barghasa.org@gmail.com.com>"]
description = "An async, no_std-compatible MQTT client for embedded systems using Embassy."
license = "MIT OR Apache-2.0"
repository = "https://github.com/FaezBarghasa/mqtt-async-embedded"
documentation = "https://docs.rs/mqtt-async-embedded"
readme = "README.md"
keywords = ["mqtt", "async", "embedded", "embassy", "no_std"]
categories = ["embedded", "no-std", "asynchronous", "network-programming"]

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io-async = "0.6.1"
heapless = "0.9"
defmt = { version = "1.0.1", optional = true }
embassy-time = "0.5.0"
embassy-net = { version = "0.7", optional = true }
async-trait = "0.1"
nom = { version = "8", optional = true }
futures = { version = "0.3.30", default-features = false }

# Dependencies for examples
log = { version = "0.4", optional = true }
env_logger = { version = "0.11", optional = true }
embassy-executor = { version = "0.9.1", optional = true }
static_cell = { version = "2.1.0", optional = true }
embassy-sync = { version = "0.7.2", optional = true }
tokio = { version = "1", features = ["full"], optional = true }



[features]
default = []
std = ["dep:tokio", "dep:log", "dep:env_logger", "dep:embassy-executor", "dep:static_cell", "dep:embassy-sync", "embassy-time/std"]
v5 = []
defmt = ["dep:defmt"]
nom = ["dep:nom"]
transport-smoltcp = ["dep:embassy-net", "embassy-net/tcp", "embassy-net/proto-ipv4", "embassy-net/medium-ethernet"]


[[example]]
name = "desktop_mock"
required-features = ["std"]
path = "examples/desktop_mock.rs"

[[example]]
name = "esp8266_uart"
path = "examples/esp8266_uart.rs"

[[example]]
name = "smoltcp_ethernet"
path = "examples/smoltcp_ethernet.rs"

